
version: '3.8'
###################################################################################
services:
###################################################################################
  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always
###################################################################################
  evaluation-service:
    build:
      context: ./services/evaluation-service
    ports:
      - "5050:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always
###################################################################################
  intern-management:
    build:
      context: ./services/intern-management
    ports:
      - "3010:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always
###################################################################################
  file-service:
    build:
      context: ./services/file-service
    ports:
      - "3020:3000"
    env_file:
      - .env
    restart: always
###################################################################################
  notification-service:
    build:
      context: ./services/notification-service
    ports:
      - "3030:3000"
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - .env
    restart: always
###################################################################################
###################################################################################
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
###################################################################################
###################################################################################
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
###################################################################################
###################################################################################
volumes:
  mongo-data:
