
version: '3.8'

services:
  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=interns
      - DB_USER=root
      - DB_PASSWORD=

  evaluation-service:
    build:
      context: ./services/evaluation-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql

  intern-management:
    build:
      context: ./services/intern-management
    ports:
      - "3001:3000"
    depends_on:
      - mysql

  file-service:
    build:
      context: ./services/file-service
    ports:
      - "3002:3000"

  notification-service:
    build:
      context: ./services/notification-service
    ports:
      - "3003:3000"
    environment:
      - PORT=3003
      - MONGO_URI=mongodb://mongo:27017/notification-service
      - AMQP_URL=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: interns
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mongo-data:
  mysql-data:

